---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deplopyment
    author: hbc
spec:
  replicas: 2
  selector:
    matchLabels:
      name: postgres-deplopyment
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-deplopyment
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: hbc
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_DB
              value: mydb]
...
