---
apiVersion: v1
kind: Service
metadata:
  name: voting-service-deployment-service
spec:
  type: loadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
     name: voting-app-deployment


